export * from "@/components/artificial-intelligence/AIPanel";
export * from "@/components/documentation-browser/BrowserPanel";
export * from "@/components/marketplace-extensions/MarketplacePanel";
export * from "./DockPanel";
export * from "@/components/marketplace-extensions/ExtensionsPanel";
export * from "@/components/terminal-console/TerminalPanel";
export * from "@/components/sidebar-panels/SearchPanel";
export * from "@/components/sidebar-panels/GitPanel";
export * from "@/components/file-management/ProjectPanel";
